<?php
return array(
    'createTables' => array(
        'cmis:meta_types' => array(
            'localName' => 'cmis:meta_types',
            'column' => array(
                'id'                       => array('type' => 'Varchar',  'nullable' => false, 'length' => 255,),
                'localName'                => array('type' => 'Varchar',  'nullable' => false, 'length' => 255,),
                'localNamespace'           => array('type' => 'Varchar',  'nullable' => true,  'length' => 255,),
                'queryName'                => array('type' => 'Varchar',  'nullable' => false, 'length' => 255,),
                'displayName'              => array('type' => 'Varchar',  'nullable' => false, 'length' => 255,),
                'baseId'                   => array('type' => 'Varchar',  'nullable' => false, 'length' => 255,),
                'parentId'                 => array('type' => 'Varchar',  'nullable' => true,  'length' => 255,),
                'description'              => array('type' => 'Varchar',  'nullable' => true,  'length' => 255,),
                'creatable'                => array('type' => 'Boolean',  'nullable' => false,),
                'fileable'                 => array('type' => 'Boolean',  'nullable' => false,),
                'queryable'                => array('type' => 'Boolean',  'nullable' => false,),
                'controllablePolicy'       => array('type' => 'Boolean',  'nullable' => false,),
                'controllableACL'          => array('type' => 'Boolean',  'nullable' => false,),
                'fulltextIndexed'          => array('type' => 'Boolean',  'nullable' => false,),
                'includedInSupertypeQuery' => array('type' => 'Boolean',  'nullable' => false,),
                'typeMutability.create'    => array('type' => 'Boolean',  'nullable' => false,),
                'typeMutability.update'    => array('type' => 'Boolean',  'nullable' => false,),
                'typeMutability.delete'    => array('type' => 'Boolean',  'nullable' => false,),
                'typeSpecific'             => array('type' => 'Varchar',  'nullable' => false, 'length' => 2048,),
            ),
            'constraint' => array(
                array('type' => 'PrimaryKey', 'columns' => array('id')),
            ),
        ),
        'cmis:meta_properties' => array(
            'column' => array(
                'propertyId'     => array('type' => 'Varchar',  'nullable' => false, 'length' => 255,),
                'localName'      => array('type' => 'Varchar',  'nullable' => false, 'length' => 255,),
                'localNamespace' => array('type' => 'Varchar',  'nullable' => false, 'length' => 255,),
                'queryName'      => array('type' => 'Varchar',  'nullable' => false, 'length' => 255,),
                'displayName'    => array('type' => 'Varchar',  'nullable' => false, 'length' => 255,),
                'description'    => array('type' => 'Varchar',  'nullable' => true,  'length' => 255,),
                'propertyType'   => array('type' => 'Varchar',  'nullable' => false, 'length' => 255,),
                'cardinality'    => array('type' => 'Varchar',  'nullable' => false, 'length' => 255,),
                'updatability'   => array('type' => 'Varchar',  'nullable' => false, 'length' => 255,),
                'required'       => array('type' => 'Boolean',  'nullable' => false,),
                'queryable'      => array('type' => 'Boolean',  'nullable' => false,),
                'orderable'      => array('type' => 'Boolean',  'nullable' => false,),
                'choices'        => array('type' => 'Boolean',  'nullable' => true,),
                'openChoice'     => array('type' => 'Boolean',  'nullable' => true,),
                'defaultValue'   => array('type' => 'Varchar',  'nullable' => true,  'length' => 255,),
                'typeSpecific'   => array('type' => 'Varchar',  'nullable' => false, 'length' => 2048,),
            ),
            'constraint' => array(
                array('type' => 'PrimaryKey', 'columns' => 'propertyId'),
            ),
        ),
        'cmis:meta_types_properties' => array(
            'column' => array(
                'propertyId'     => array('type' => 'Varchar',  'nullable' => false, 'length' => 255,),
                'typeId'         => array('type' => 'Varchar',  'nullable' => false, 'length' => 255,),
                'inherited'      => array('type' => 'Boolean',  'nullable' => false,),
                'localName'      => array('type' => 'Varchar',  'nullable' => true, 'length' => 255,),
                'localNamespace' => array('type' => 'Varchar',  'nullable' => true, 'length' => 255,),
                'defaultValue'   => array('type' => 'Varchar',  'nullable' => true,  'length' => 255,),
            ),
            'constraint' => array(
                array('type' => 'PrimaryKey', 'columns' => array('propertyId', 'typeId')),
            ),
        ),
        'cmis:object' => array(
            'localName' => 'cmis_object',
            'column' => array(
                'cmis_objectId'               => array('type' => 'Integer',    'nullable' => false, 'auto_increment' => true,),
                'cmis_baseTypeId'             => array('type' => 'Varchar',    'nullable' => false, 'length' => 255,),
                'cmis_objectTypeId'           => array('type' => 'Varchar',    'nullable' => false, 'length' => 255,),
                'cmis_secondaryObjectTypeIds' => array('type' => 'Varchar',    'nullable' => true,  'length' => 2048,),
                'cmis_name'                   => array('type' => 'Varchar',    'nullable' => false, 'length' => 255,),
                'cmis_description'            => array('type' => 'Varchar',    'nullable' => true,  'length' => 255,),
                'cmis_createdBy'              => array('type' => 'Varchar',    'nullable' => true,  'length' => 255,),
                'cmis_creationDate'           => array('type' => 'Time',       'nullable' => true,),
                'cmis_lastModifiedBy'         => array('type' => 'Varchar',    'nullable' => true, 'length' => 255,),
                'cmis_lastModificationDate'   => array('type' => 'Date',       'nullable' => true,),
                'cmis_changeToken'            => array('type' => 'BigInteger', 'nullable' => true,),
            ),
            'constraint' => array(
                array('type' => 'PrimaryKey', 'columns' => 'cmis_objectId'),
            ),
        ),
        'cmis:document' => array(
            'localName' => 'cmis_document',
            'column' => array(
                'cmis_objectId'                  => array('type' => 'Integer',    'nullable' => false,),
                'cmis_isImmutable'               => array('type' => 'Boolean',    'nullable' => true,),
                'cmis_isLatestVersion'           => array('type' => 'Boolean',    'nullable' => true,),
                'cmis_isMajorVersion'            => array('type' => 'Boolean',    'nullable' => true,),
                'cmis_isLatestMajorVersion'      => array('type' => 'Boolean',    'nullable' => true,),
                'cmis_isPrivateWorkingCopy'      => array('type' => 'Boolean',    'nullable' => true,),
                'cmis_versionLabel'              => array('type' => 'Varchar',    'nullable' => true, 'length' => 255,),
                'cmis_versionSeriesId'           => array('type' => 'Integer',    'nullable' => true,),
                'cmis_isVersionSeriesCheckedOut' => array('type' => 'Integer',    'nullable' => true,),
                'cmis_versionSeriesCheckedOutBy' => array('type' => 'Varchar',    'nullable' => true, 'length' => 255,),
                'cmis_versionSeriesCheckedOutId' => array('type' => 'Varchar',    'nullable' => true, 'length' => 255,),
                'cmis_checkinComment'            => array('type' => 'Varchar',    'nullable' => true, 'length' => 255,),
                'cmis_contentStreamLength'       => array('type' => 'Varchar',    'nullable' => true, 'length' => 255,),
                'cmis_contentStreamMimeType'     => array('type' => 'Varchar',    'nullable' => true, 'length' => 255,),
                'cmis_contentStreamFileName'     => array('type' => 'Varchar',    'nullable' => true, 'length' => 255,),
                'cmis_contentStreamId'           => array('type' => 'Integer',    'nullable' => true,),
            ),
            'constraint' => array(
                array('type' => 'PrimaryKey', 'columns' => 'cmis_objectId'),
            ),
        ),
        'cmis:folder' => array(
            'localName' => 'cmis_folder',
            'column' => array(
                'cmis_objectId'                  => array('type' => 'Integer',    'nullable' => false,),
                'cmis_parentId'                  => array('type' => 'Integer',    'nullable' => true,),
                'cmis_level'                     => array('type' => 'Integer',    'nullable' => false,),
                'cmis_leftKey'                   => array('type' => 'Integer',    'nullable' => false,),
                'cmis_rightKey'                  => array('type' => 'Integer',    'nullable' => false,),
                'cmis_path'                      => array('type' => 'Varchar',    'nullable' => true,  'length' => 2048,),
                'cmis_allowedChildObjectTypeIds' => array('type' => 'Varchar',    'nullable' => false, 'length' => 255,),
            ),
            'constraint' => array(
                array('type' => 'PrimaryKey', 'columns' => 'cmis_objectId'),
            ),
        ),
        'cmis:relationship' => array(
            'localName' => 'cmis_relationship',
            'column' => array(
                'cmis_objectId'     => array('type' => 'Integer',    'nullable' => false,),
                'cmis_sourceId'     => array('type' => 'Integer',    'nullable' => false,),
                'cmis_targetId'     => array('type' => 'Integer',    'nullable' => false,),
                'cmis_sourceTypeId' => array('type' => 'Varchar',    'nullable' => false, 'length' => 255,),
                'cmis_targetTypeId' => array('type' => 'Varchar',    'nullable' => false, 'length' => 255,),
            ),
            'constraint' => array(
                array('type' => 'PrimaryKey', 'columns' => 'cmis_objectId'),
            ),
        ),
        'cmis:policy' => array(
            'localName' => 'cmis_policy',
            'column' => array(
                'cmis_objectId'   => array('type' => 'Integer',    'nullable' => false,),
                'cmis_policyText' => array('type' => 'Varchar',    'nullable' => false, 'length' => 255,),
            ),
            'constraint' => array(
                array('type' => 'PrimaryKey', 'columns' => 'cmis_objectId'),
            ),
        ),
    ),
    'insertTablesData' => array(
        array(
            'table'  => 'cmis:meta_types',
            'values' => array(
                array(
                    'id'                       => 'cmis:document',
                    'parentId'                 => null,
                    'queryName'                => 'cmis:document',
                    'displayName'              => 'cmis:document',
                    'localName'                => 'cmis_document',
                    'localNamespace'           => 'cmis_document',
                    'baseId'                   => 'cmis:document',
                    'description'              => '',
                    'creatable'                => true,
                    'fileable'                 => true,
                    'queryable'                => true,
                    'controllablePolicy'       => false,
                    'controllableACL'          => false,
                    'fulltextIndexed'          => false,
                    'includedInSupertypeQuery' => true,
                    'typeMutability.create'    => true,
                    'typeMutability.update'    => true,
                    'typeMutability.delete'    => true,
                    'typeSpecific'             => '{"versionable":null,"contentStreamAllowed":null}',
                ),
                array(
                    'id'                       => 'cmis:folder',
                    'parentId'                 => null,
                    'queryName'                => 'cmis:folder',
                    'displayName'              => 'cmis:folder',
                    'localName'                => 'cmis_folder',
                    'localNamespace'           => 'cmis_folder',
                    'baseId'                   => 'cmis:folder',
                    'description'              => '',
                    'creatable'                => true,
                    'fileable'                 => true,
                    'queryable'                => true,
                    'controllablePolicy'       => false,
                    'controllableACL'          => false,
                    'fulltextIndexed'          => false,
                    'includedInSupertypeQuery' => true,
                    'typeMutability.create'    => true,
                    'typeMutability.update'    => true,
                    'typeMutability.delete'    => true,
                    'typeSpecific'             => '{}',
                ),
                array(
                    'id'                       => 'cmis:relationship',
                    'parentId'                 => null,
                    'queryName'                => 'cmis:relationship',
                    'displayName'              => 'cmis:relationship',
                    'localName'                => 'cmis_relationship',
                    'localNamespace'           => 'cmis_relationship',
                    'baseId'                   => 'cmis:relationship',
                    'description'              => '',
                    'creatable'                => true,
                    'fileable'                 => false,
                    'queryable'                => true,
                    'controllablePolicy'       => false,
                    'controllableACL'          => false,
                    'fulltextIndexed'          => false,
                    'includedInSupertypeQuery' => true,
                    'typeMutability.create'    => true,
                    'typeMutability.update'    => true,
                    'typeMutability.delete'    => true,
                    'typeSpecific'             => '{"allowedSourceTypes":null,"allowedTargetTypes":null}',
                ),
                array(
                    'id'                       => 'cmis:policy',
                    'parentId'                 => null,
                    'queryName'                => 'cmis:policy',
                    'displayName'              => 'cmis:policy',
                    'localName'                => 'cmis_policy',
                    'localNamespace'           => 'cmis_policy',
                    'baseId'                   => 'cmis:policy',
                    'description'              => '',
                    'creatable'                => true,
                    'fileable'                 => true,
                    'queryable'                => true,
                    'controllablePolicy'       => false,
                    'controllableACL'          => false,
                    'fulltextIndexed'          => false,
                    'includedInSupertypeQuery' => true,
                    'typeMutability.create'    => true,
                    'typeMutability.update'    => true,
                    'typeMutability.delete'    => true,
                    'typeSpecific'             => '{}',
                ),
                array(
                    'id'                       => 'cmis:item',
                    'parentId'                 => null,
                    'queryName'                => 'cmis:item',
                    'displayName'              => 'cmis:item',
                    'localName'                => 'cmis_item',
                    'localNamespace'           => 'cmis_item',
                    'baseId'                   => 'cmis:item',
                    'description'              => '',
                    'creatable'                => false,
                    'fileable'                 => true,
                    'queryable'                => true,
                    'controllablePolicy'       => false,
                    'controllableACL'          => false,
                    'fulltextIndexed'          => false,
                    'includedInSupertypeQuery' => true,
                    'typeMutability.create'    => true,
                    'typeMutability.update'    => true,
                    'typeMutability.delete'    => true,
                    'typeSpecific'             => '{}',
                ),
            ),
        ),
        array(
            'table'  => 'cmis:meta_properties', // Common
            'values' => array(
                array(
                    'propertyId'     => 'cmis:objectId',
                    'propertyType'   => 'xs:id',
                    'localName'      => 'cmis_objectId',
                    'localNamespace' => 'cmis_object',
                    'queryName'      => 'cmis:objectId',
                    'displayName'    => 'cmis:objectId',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readonly',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:baseTypeId',
                    'propertyType'   => 'xs:id',
                    'localName'      => 'cmis_baseTypeId',
                    'localNamespace' => 'cmis_object',
                    'queryName'      => 'cmis:baseTypeId',
                    'displayName'    => 'cmis:baseTypeId',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readonly',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:objectTypeId',
                    'propertyType'   => 'xs:id',
                    'localName'      => 'cmis_objectTypeId',
                    'localNamespace' => 'cmis_object',
                    'queryName'      => 'cmis:objectTypeId',
                    'displayName'    => 'cmis:objectTypeId',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'oncreate',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:secondaryObjectTypeIds',
                    'propertyType'   => 'xs:id',
                    'localName'      => 'cmis_secondaryObjectTypeIds',
                    'localNamespace' => 'cmis_object',
                    'queryName'      => 'cmis:secondaryObjectTypeIds',
                    'displayName'    => 'cmis:secondaryObjectTypeIds',
                    'description'    => null,
                    'cardinality'    => 'multi',
                    'updatability'   => 'readwrite',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:name',
                    'propertyType'   => 'xs:string',
                    'localName'      => 'cmis_name',
                    'localNamespace' => 'cmis_object',
                    'queryName'      => 'cmis:name',
                    'displayName'    => 'cmis:name',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readwrite',
                    'required'       => true,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:description',
                    'propertyType'   => 'xs:string',
                    'localName'      => 'cmis_description',
                    'localNamespace' => 'cmis_object',
                    'queryName'      => 'cmis:description',
                    'displayName'    => 'cmis:description',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readwrite',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:createdBy',
                    'propertyType'   => 'xs:string',
                    'localName'      => 'cmis_createdBy',
                    'localNamespace' => 'cmis_object',
                    'queryName'      => 'cmis:createdBy',
                    'displayName'    => 'cmis:createdBy',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readonly',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:creationDate',
                    'propertyType'   => 'xs:dateTime',
                    'localName'      => 'cmis_creationDate',
                    'localNamespace' => 'cmis_object',
                    'queryName'      => 'cmis:creationDate',
                    'displayName'    => 'cmis:creationDate',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readonly',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:lastModifiedBy',
                    'propertyType'   => 'xs:string',
                    'localName'      => 'cmis_lastModifiedBy',
                    'localNamespace' => 'cmis_object',
                    'queryName'      => 'cmis:lastModifiedBy',
                    'displayName'    => 'cmis:lastModifiedBy',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readonly',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:lastModificationDate',
                    'propertyType'   => 'xs:dateTime',
                    'localName'      => 'cmis_lastModificationDate',
                    'localNamespace' => 'cmis_object',
                    'queryName'      => 'cmis:lastModificationDate',
                    'displayName'    => 'cmis:lastModificationDate',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readonly',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:changeToken',
                    'propertyType'   => 'xs:string',
                    'localName'      => 'cmis_changeToken',
                    'localNamespace' => 'cmis_object',
                    'queryName'      => 'cmis:changeToken',
                    'displayName'    => 'cmis:changeToken',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readonly',
                    'required'       => false,
                    'queryable'      => false,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
            ),
        ),
        array(
            'table'  => 'cmis:meta_properties', // Document
            'values' => array(
                array(
                    'propertyId'     => 'cmis:isImmutable',
                    'propertyType'   => 'xs:boolean',
                    'localName'      => 'cmis_isImmutable',
                    'localNamespace' => 'cmis_document',
                    'queryName'      => 'cmis:isImmutable',
                    'displayName'    => 'cmis:isImmutable',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'oncreate',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:isLatestVersion',
                    'propertyType'   => 'xs:boolean',
                    'localName'      => 'cmis_isLatestVersion',
                    'localNamespace' => 'cmis_document',
                    'queryName'      => 'cmis:isLatestVersion',
                    'displayName'    => 'cmis:isLatestVersion',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readonly',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:isMajorVersion',
                    'propertyType'   => 'xs:boolean',
                    'localName'      => 'cmis_isMajorVersion',
                    'localNamespace' => 'cmis_document',
                    'queryName'      => 'cmis:isMajorVersion',
                    'displayName'    => 'cmis:isMajorVersion',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readonly',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:isLatestMajorVersion',
                    'propertyType'   => 'xs:boolean',
                    'localName'      => 'cmis_isLatestMajorVersion',
                    'localNamespace' => 'cmis_document',
                    'queryName'      => 'cmis:isLatestMajorVersion',
                    'displayName'    => 'cmis:isLatestMajorVersion',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readonly',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:isPrivateWorkingCopy',
                    'propertyType'   => 'xs:boolean',
                    'localName'      => 'cmis_isPrivateWorkingCopy',
                    'localNamespace' => 'cmis_document',
                    'queryName'      => 'cmis:isPrivateWorkingCopy',
                    'displayName'    => 'cmis:isPrivateWorkingCopy',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readonly',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:versionLabel',
                    'propertyType'   => 'xs:string',
                    'localName'      => 'cmis_versionLabel',
                    'localNamespace' => 'cmis_document',
                    'queryName'      => 'cmis:versionLabel',
                    'displayName'    => 'cmis:versionLabel',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readonly',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:versionSeriesId',
                    'propertyType'   => 'xs:id',
                    'localName'      => 'cmis_versionSeriesId',
                    'localNamespace' => 'cmis_document',
                    'queryName'      => 'cmis:versionSeriesId',
                    'displayName'    => 'cmis:versionSeriesId',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readonly',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:isVersionSeriesCheckedOut',
                    'propertyType'   => 'xs:id',
                    'localName'      => 'cmis_isVersionSeriesCheckedOut',
                    'localNamespace' => 'cmis_document',
                    'queryName'      => 'cmis:isVersionSeriesCheckedOut',
                    'displayName'    => 'cmis:isVersionSeriesCheckedOut',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readonly',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:versionSeriesCheckedOutBy',
                    'propertyType'   => 'xs:string',
                    'localName'      => 'cmis_versionSeriesCheckedOutBy',
                    'localNamespace' => 'cmis_document',
                    'queryName'      => 'cmis:versionSeriesCheckedOutBy',
                    'displayName'    => 'cmis:versionSeriesCheckedOutBy',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readonly',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:versionSeriesCheckedOutId',
                    'propertyType'   => 'xs:id',
                    'localName'      => 'cmis_versionSeriesCheckedOutId',
                    'localNamespace' => 'cmis_document',
                    'queryName'      => 'cmis:versionSeriesCheckedOutId',
                    'displayName'    => 'cmis:versionSeriesCheckedOutId',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readonly',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:checkinComment',
                    'propertyType'   => 'xs:string',
                    'localName'      => 'cmis_checkinComment',
                    'localNamespace' => 'cmis_document',
                    'queryName'      => 'cmis:checkinComment',
                    'displayName'    => 'cmis:checkinComment',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readonly',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:contentStreamLength',
                    'propertyType'   => 'xs:integer',
                    'localName'      => 'cmis_contentStreamLength',
                    'localNamespace' => 'cmis_document',
                    'queryName'      => 'cmis:contentStreamLength',
                    'displayName'    => 'cmis:contentStreamLength',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readonly',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:contentStreamMimeType',
                    'propertyType'   => 'xs:string',
                    'localName'      => 'cmis_contentStreamMimeType',
                    'localNamespace' => 'cmis_document',
                    'queryName'      => 'cmis:contentStreamMimeType',
                    'displayName'    => 'cmis:contentStreamMimeType',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readonly',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:contentStreamFileName',
                    'propertyType'   => 'xs:string',
                    'localName'      => 'cmis_contentStreamFileName',
                    'localNamespace' => 'cmis_document',
                    'queryName'      => 'cmis:contentStreamFileName',
                    'displayName'    => 'cmis:contentStreamFileName',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readonly',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:contentStreamId',
                    'propertyType'   => 'xs:id',
                    'localName'      => 'cmis_contentStreamId',
                    'localNamespace' => 'cmis_document',
                    'queryName'      => 'cmis:contentStreamId',
                    'displayName'    => 'cmis:contentStreamId',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readonly',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
            ),
        ),
        array(
            'table'  => 'cmis:meta_properties', // Folder
            'values' => array(
                array(
                    'propertyId'     => 'cmis:parentId',
                    'propertyType'   => 'xs:id',
                    'localName'      => 'cmis_parentId',
                    'localNamespace' => 'cmis_folder',
                    'queryName'      => 'cmis:parentId',
                    'displayName'    => 'cmis:parentId',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'oncreate',
                    'required'       => true,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:path',
                    'propertyType'   => 'xs:string',
                    'localName'      => 'cmis_path',
                    'localNamespace' => 'cmis_folder',
                    'queryName'      => 'cmis:path',
                    'displayName'    => 'cmis:path',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readonly',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:allowedChildObjectTypeIds',
                    'propertyType'   => 'xs:id',
                    'localName'      => 'cmis_allowedChildObjectTypeIds',
                    'localNamespace' => 'cmis_folder',
                    'queryName'      => 'cmis:allowedChildObjectTypeIds',
                    'displayName'    => 'cmis:allowedChildObjectTypeIds',
                    'description'    => null,
                    'cardinality'    => 'multi',
                    'updatability'   => 'readonly',
                    'required'       => false,
                    'queryable'      => false,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                //Folder Repository Specific
                array(
                    'propertyId'     => 'cmis:level',
                    'propertyType'   => 'xs:integer',
                    'localName'      => 'cmis_level',
                    'localNamespace' => 'cmis_folder',
                    'queryName'      => 'cmis:level',
                    'displayName'    => 'cmis:level',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readonly',
                    'required'       => false,
                    'queryable'      => false,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:leftKey',
                    'propertyType'   => 'xs:integer',
                    'localName'      => 'cmis_leftKey',
                    'localNamespace' => 'cmis_folder',
                    'queryName'      => 'cmis:leftKey',
                    'displayName'    => 'cmis:leftKey',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readonly',
                    'required'       => false,
                    'queryable'      => false,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:rightKey',
                    'propertyType'   => 'xs:integer',
                    'localName'      => 'cmis_rightKey',
                    'localNamespace' => 'cmis_folder',
                    'queryName'      => 'cmis:rightKey',
                    'displayName'    => 'cmis:rightKey',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'readonly',
                    'required'       => false,
                    'queryable'      => false,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
            ),
        ),
        array(
            'table'  => 'cmis:meta_properties', // Relationship
            'values' => array(
                array(
                    'propertyId'     => 'cmis:sourceId',
                    'propertyType'   => 'xs:id',
                    'localName'      => 'cmis_sourceId',
                    'localNamespace' => 'cmis_relationship',
                    'queryName'      => 'cmis:sourceId',
                    'displayName'    => 'cmis:sourceId',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'oncreate',
                    'required'       => true,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:targetId',
                    'propertyType'   => 'xs:id',
                    'localName'      => 'cmis_targetId',
                    'localNamespace' => 'cmis_relationship',
                    'queryName'      => 'cmis:targetId',
                    'displayName'    => 'cmis:targetId',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'oncreate',
                    'required'       => true,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:sourceTypeId',
                    'propertyType'   => 'xs:id',
                    'localName'      => 'cmis_sourceTypeId',
                    'localNamespace' => 'cmis_relationship',
                    'queryName'      => 'cmis:sourceTypeId',
                    'displayName'    => 'cmis:sourceTypeId',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'oncreate',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
                array(
                    'propertyId'     => 'cmis:targetTypeId',
                    'propertyType'   => 'xs:id',
                    'localName'      => 'cmis_targetTypeId',
                    'localNamespace' => 'cmis_relationship',
                    'queryName'      => 'cmis:targetTypeId',
                    'displayName'    => 'cmis:targetTypeId',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'oncreate',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
            ),
        ),
        array(
            'table'  => 'cmis:meta_properties', // Policy
            'values' => array(
                array(
                    'propertyId'     => 'cmis:policyText',
                    'propertyType'   => 'xs:string',
                    'localName'      => 'cmis_policyText',
                    'localNamespace' => 'cmis_policy',
                    'queryName'      => 'cmis:policyText',
                    'displayName'    => 'cmis:policyText',
                    'description'    => null,
                    'cardinality'    => 'single',
                    'updatability'   => 'oncreate', //'readonly',
                    'required'       => false,
                    'queryable'      => true,
                    'orderable'      => false,
                    'choices'        => null,
                    'openChoice'     => null,
                    'defaultValue'   => null,
                ),
            ),
        ),
        array(
            'table'  => 'cmis:meta_types_properties', // Relationship
            'values' => array(
                array(
                    'typeId'         => 'cmis:document',
                    'propertyId'     => 'cmis:objectId',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:document',
                    'propertyId'     => 'cmis:baseTypeId',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => 'cmis:document',
                ),
                array(
                    'typeId'         => 'cmis:document',
                    'propertyId'     => 'cmis:objectTypeId',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => 'cmis:document',
                ),
                array(
                    'typeId'         => 'cmis:document',
                    'propertyId'     => 'cmis:secondaryObjectTypeIds',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:document',
                    'propertyId'     => 'cmis:name',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:document',
                    'propertyId'     => 'cmis:description',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:document',
                    'propertyId'     => 'cmis:createdBy',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:document',
                    'propertyId'     => 'cmis:creationDate',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:document',
                    'propertyId'     => 'cmis:lastModifiedBy',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:document',
                    'propertyId'     => 'cmis:lastModificationDate',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:document',
                    'propertyId'     => 'cmis:changeToken',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:document',
                    'propertyId'     => 'cmis:isImmutable',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:document',
                    'propertyId'     => 'cmis:isLatestVersion',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:document',
                    'propertyId'     => 'cmis:isMajorVersion',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:document',
                    'propertyId'     => 'cmis:isLatestMajorVersion',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:document',
                    'propertyId'     => 'cmis:isPrivateWorkingCopy',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:document',
                    'propertyId'     => 'cmis:versionLabel',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:document',
                    'propertyId'     => 'cmis:versionSeriesId',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:document',
                    'propertyId'     => 'cmis:isVersionSeriesCheckedOut',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:document',
                    'propertyId'     => 'cmis:versionSeriesCheckedOutBy',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:document',
                    'propertyId'     => 'cmis:versionSeriesCheckedOutId',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:document',
                    'propertyId'     => 'cmis:checkinComment',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:document',
                    'propertyId'     => 'cmis:contentStreamLength',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:document',
                    'propertyId'     => 'cmis:contentStreamMimeType',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:document',
                    'propertyId'     => 'cmis:contentStreamFileName',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:document',
                    'propertyId'     => 'cmis:contentStreamId',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                // Folder
                array(
                    'typeId'         => 'cmis:folder',
                    'propertyId'     => 'cmis:objectId',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:folder',
                    'propertyId'     => 'cmis:baseTypeId',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => 'cmis:folder',
                ),
                array(
                    'typeId'         => 'cmis:folder',
                    'propertyId'     => 'cmis:objectTypeId',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => 'cmis:folder',
                ),
                array(
                    'typeId'         => 'cmis:folder',
                    'propertyId'     => 'cmis:secondaryObjectTypeIds',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:folder',
                    'propertyId'     => 'cmis:name',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:folder',
                    'propertyId'     => 'cmis:description',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:folder',
                    'propertyId'     => 'cmis:createdBy',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:folder',
                    'propertyId'     => 'cmis:creationDate',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:folder',
                    'propertyId'     => 'cmis:lastModifiedBy',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:folder',
                    'propertyId'     => 'cmis:lastModificationDate',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:folder',
                    'propertyId'     => 'cmis:changeToken',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:folder',
                    'propertyId'     => 'cmis:parentId',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:folder',
                    'propertyId'     => 'cmis:path',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:folder',
                    'propertyId'     => 'cmis:allowedChildObjectTypeIds',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                // Folder Repository Specific
                array(
                    'typeId'         => 'cmis:folder',
                    'propertyId'     => 'cmis:level',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:folder',
                    'propertyId'     => 'cmis:leftKey',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:folder',
                    'propertyId'     => 'cmis:rightKey',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                // Relationship
                array(
                    'typeId'         => 'cmis:relationship',
                    'propertyId'     => 'cmis:objectId',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:relationship',
                    'propertyId'     => 'cmis:baseTypeId',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => 'cmis:relationship',
                ),
                array(
                    'typeId'         => 'cmis:relationship',
                    'propertyId'     => 'cmis:objectTypeId',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => 'cmis:relationship',
                ),
                array(
                    'typeId'         => 'cmis:relationship',
                    'propertyId'     => 'cmis:secondaryObjectTypeIds',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:relationship',
                    'propertyId'     => 'cmis:name',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:relationship',
                    'propertyId'     => 'cmis:description',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:relationship',
                    'propertyId'     => 'cmis:createdBy',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:relationship',
                    'propertyId'     => 'cmis:creationDate',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:relationship',
                    'propertyId'     => 'cmis:lastModifiedBy',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:relationship',
                    'propertyId'     => 'cmis:lastModificationDate',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:relationship',
                    'propertyId'     => 'cmis:changeToken',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:relationship',
                    'propertyId'     => 'cmis:sourceId',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:relationship',
                    'propertyId'     => 'cmis:targetId',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:relationship',
                    'propertyId'     => 'cmis:sourceTypeId',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:relationship',
                    'propertyId'     => 'cmis:targetTypeId',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                // Policy
                array(
                    'typeId'         => 'cmis:policy',
                    'propertyId'     => 'cmis:objectId',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:policy',
                    'propertyId'     => 'cmis:baseTypeId',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => 'cmis:policy',
                ),
                array(
                    'typeId'         => 'cmis:policy',
                    'propertyId'     => 'cmis:objectTypeId',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => 'cmis:policy',
                ),
                array(
                    'typeId'         => 'cmis:policy',
                    'propertyId'     => 'cmis:secondaryObjectTypeIds',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:policy',
                    'propertyId'     => 'cmis:name',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:policy',
                    'propertyId'     => 'cmis:description',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:policy',
                    'propertyId'     => 'cmis:createdBy',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:policy',
                    'propertyId'     => 'cmis:creationDate',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:policy',
                    'propertyId'     => 'cmis:lastModifiedBy',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:policy',
                    'propertyId'     => 'cmis:lastModificationDate',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:policy',
                    'propertyId'     => 'cmis:changeToken',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:policy',
                    'propertyId'     => 'cmis:policyText',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                // Item
                array(
                    'typeId'         => 'cmis:item',
                    'propertyId'     => 'cmis:objectId',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:item',
                    'propertyId'     => 'cmis:baseTypeId',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => 'cmis:item',
                ),
                array(
                    'typeId'         => 'cmis:item',
                    'propertyId'     => 'cmis:objectTypeId',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => 'cmis:item',
                ),
                array(
                    'typeId'         => 'cmis:item',
                    'propertyId'     => 'cmis:secondaryObjectTypeIds',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:item',
                    'propertyId'     => 'cmis:name',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:item',
                    'propertyId'     => 'cmis:description',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:item',
                    'propertyId'     => 'cmis:createdBy',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:item',
                    'propertyId'     => 'cmis:creationDate',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:item',
                    'propertyId'     => 'cmis:lastModifiedBy',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:item',
                    'propertyId'     => 'cmis:lastModificationDate',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
                array(
                    'typeId'         => 'cmis:item',
                    'propertyId'     => 'cmis:changeToken',
                    'inherited'      => false,
                    'localName'      => null,
                    'localNamespace' => null,
                    'defaultValue'   => null,
                ),
            ),
        ),
        //======================================================================
        // InsertRoot folder
        array(
            'table'  => 'cmis_object',
            'values' => array(
                array(
                    'cmis_objectId'             => 1,
                    'cmis_baseTypeId'           => 'cmis:folder',
                    'cmis_objectTypeId'         => 'cmis:folder',
                    'cmis_name'                 => '/',
                    'cmis_description'          => 'root folder',
                    'cmis_createdBy'            => 'robot',
                    'cmis_creationDate'         => null,
                    'cmis_lastModifiedBy'       => 'robot',
                    'cmis_lastModificationDate' => null,
                ),
            ),
        ),
        array(
            'table'  => 'cmis_folder',
            'values' => array(
                array(
                    //'cmis_objectId' => $adapter->getDriver()->getLastGeneratedValue(),
                    'cmis_objectId' => 1,
                    'cmis_parentId' => null,
                    'cmis_path'     => '/',
                    'cmis_level'    => 0,
                    'cmis_leftKey'  => 1,
                    'cmis_rightKey' => 2,
                ),
            ),
        ),
        //======================================================================
    ),
);