<table>
    <thead>
        <tr style="text-align: left">
            <th colspan="3">
                <?=$parent['properties']['cmis:name']?>
            </th>
        </tr>
        <tr>
            <th>id</th>
            <th>name</th>
            <th>documents</th>
        </tr>
    </thead>
    <tbody>
        <?php 
        $parentLevel = $parent['properties']['cmis:level'];
        foreach($folders as $folder) :?>
            <tr>
                <td>
                    <?=$folder['cmis:objectId']?>
                </td>
                <td>
                    <?=str_repeat('&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;', $folders->getDepth() - $parentLevel)?>
                    <a href="<?php
                        $references['edit']["params"]["containers"]["content"]["object"]=$folder['cmis:objectId'];
                        echo $this->url($references['edit']);
                    ?>"><?=$folder['cmis:name']?></a>
                </td>
                <td>
                    <a href="<?php
                        $references['documents']["params"]["containers"]["content"]["folder"]=$folder['cmis:objectId'];
                        echo $this->url($references['documents']);
                    ?>">documents</a>
                </td>
            </tr>
        <?php endforeach;?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" style="text-align: center">
                <a class="aButton" href="<?=$this->url($references['create']);?>">CreateObject</a>
            </td>
        </tr>
    </tfoot>
</table>